### ISSUE TITLE
Installation instruction for Raspberry PI hazy

### ISSUE THREAD

**Issue by philippbruhin** [pamasol/IDPA-Landrunner#1]
@marvinbueeler thank you for updating the installation instruction for Raspberry Pi in the [readme](https://github.com/pamasol/IDPA-Landrunner/blob/e578fcfa6a682ce7315c829516ac48908aedad69/README.md) section. Unfortunately in my opinion there are still some issue:

**Step 2:** You explain that user has to clone your repo. But in which folder would you run that command? Please make a suggestion.

**Step 3:** Please note that this is for *pygame* and not for Python in general. I don't think that pygame comes with Raspbian. So `pip install -r requirements.txt` has to be executed either way. What do you think?

 **Step 4:** Did you really edit the file with nano? I think this is a bit too advanced for first timers in this area. Please describe how to open and edit with another text editor.

Please verify and update the instructions or leave a feedback when you do not agree. Thanks, Philipp

**Comment by marvinbueeler** [comment]
I updated the readme again for step 2 and 4. Theres no need to change step 3. Pygame already comes with raspbian and should not be needed to be installed manually.

**Comment by philippbruhin** [comment]
Thank you for your feedback @marvinbueeler and updating the readme file. Now it is ok for me as well 👍 

I checked [debian buster package](https://packages.debian.org/buster/python-pygame) and it looks as described by you, that pygame comes with the operating system. The website says *This is the Python 2 version of the package.* and that was may the reason why the game did not work with python3 on Raspberry Pi.

I will close this issue. Once again thank you for your work.
